---
title: 'Lab Report 3'
author: "By: Abhishek Shah, Ravi Seth, Tanya Ralliaram"
geometry: margin=.75in
output:
  pdf_document: default
  word_document: default
  html_document:
    df_print: paged
    theme: cosmo
header-includes:
- \usepackage{graphicx}
- \usepackage{color}
graphics: yes
fontsize: 11pt
always_allow_html: true
---

```{r, message=FALSE}
# Insert necessary packages
library(keras)
library(tidyverse)
library(neuralnet)
```

## Question 1: Classification using NNets
```{r}
mnist <- dataset_fashion_mnist()
```

### 1.1: Get Data
```{r}
x_train <- mnist$train$x
y_train <- mnist$train$y
x_test <- mnist$test$x
y_test <- mnist$test$y

dim(x_train)
dim(x_test)
```

### 1.2: Plot
```{r}
par(pty="s") # for keeping the aspect ratio 1:1
trouser <- x_train[107,28:1,1:28]
image(t(trouser), col = gray.colors(256), axes = FALSE)
bag <- x_train[213,28:1,1:28]
image(t(bag), col = gray.colors(256), axes = FALSE)
boot <- x_train[1,28:1,1:28]
image(t(boot), col = gray.colors(256), axes = FALSE)
```

### 1.3: Process the dataset
```{r}
# reshape
x_train <- array_reshape(x_train, c(nrow(x_train), 784))
x_test <- array_reshape(x_test, c(nrow(x_test), 784))

# rescale
x_train <- x_train / 255
x_test <- x_test / 255

y_train <- to_categorical(y_train, 10)
y_test  <- to_categorical(y_test, 10)
```

### 1.4: Fit a Shallow Network
```{r}

```

### 1.5: Fit a Deep Neural Network
```{r}

```